project:
  type: website
  output-dir: docs

website:
  title: "Siqi Fei/ Fermi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Siqi_Fei-Resume.pdf
        text: CV
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



